@echo off
echo Starting Mobile Money Backend...
start /B call mvnw.cmd spring-boot:run
echo Waiting 15 seconds for the server to start...
timeout /t 15 /nobreak >nul
echo Opening Dashboard...
start http://localhost:8080/dashboard.html